dist: xenial

language: python

python:
  - "3.7.2"

virtualenv:
  system_site_packages: true

install:
  - pip install -r requirements.txt

script:
  - pytest

after_script: cd ~

deploy:
  provider: script
  script: python3 aliens.py
  on:
    branch: travis
